ecommerce/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name="cart"),
    path('add_cartitem/<int:product_id>',
         views.add_cartitem, name="add_cartitem"),
    path('remove_cartitem/<int:cartitem_id>',
         views.remove_cartitem, name="remove_cartitem"),

]

ecommerce/ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

from ecommerce import settings
from orders.views import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', 'products')),
    path('orders/', include('orders.urls', 'orders')),
    path('cart/', include('cart.urls', 'cart')),
    path('account/', include('users.urls', 'users')),
]


handler404 = page_not_found

ecommerce/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('registration', views.registration, name='registration'),
    path('login', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    # path('logout', views.Logout.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),

]

ecommerce/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class CommercialInfo(models.Model):
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    email_verified = models.BooleanField(default=False)
    phone_verified = models.BooleanField(default=False)
    profile_icon = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

    class Meta:
        abstract = True


class User(AbstractUser, CommercialInfo):
    ROLE_CHOICES = [
        ('buyer', 'Buyer'),
        ('seller', 'Seller'),
        ('admin', 'Admin'),
    ]

    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='buyer')
    birth_date = models.DateField(blank=True, null=True)
    shop_name = models.CharField(max_length=255, blank=True, null=True)     # ?
    shop_description = models.TextField(blank=True, null=True)              # ?
    iban = models.CharField(max_length=34, blank=True, null=True)

    def __str__(self):
        if self.role == "seller" and self.shop_name:
            return self.shop_name
        return self.username


class ShopProfile(CommercialInfo):
    user = models.OneToOneField('User', on_delete=models.CASCADE, related_name="shop_profile")
    shop_name = models.CharField(max_length=255, blank=True, null=True)
    shop_description = models.TextField(blank=True, null=True)
    iban = models.CharField(max_length=34, blank=True, null=True)

    def __str__(self):
        return self.shop_name or f"Shop of {self.user.username}"

ecommerce/users/forms.py
from .models import User, ShopProfile
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)


class LoginUser(AuthenticationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username',
                  'role', 'phone_number']
        # widgets = {
        #     'first_name': forms.TextInput(attrs={'class': 'form-input'}),
        #     'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        #     'email': forms.EmailField(attrs={'class': 'form-input'}),
        # }
        # labels = {'first_name': 'Url'}


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'registration__input', 'placeholder': 'Enter first name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'registration__input', 'placeholder': 'Enter last name'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'registration__input', 'placeholder': 'Enter username'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'registration__input', 'placeholder': 'Enter email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'registration__input', 'placeholder': 'Enter password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'registration__input', 'placeholder': 'Confirm password'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'email', 'password1', 'password2')
        
class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'registration__input', 'placeholder': 'Name'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'registration__input', 'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ('username', 'password')

ecommerce/users/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .forms import UserRegistrationForm, UserLoginForm
from django.http.response import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import auth
from users.models import User
from cart.models import Cart

# Create your views here.class MyView(View):


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            Cart.objects.create(user=user)
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    print(request.POST)
    context = {'form': form}
    return render(request, template_name='users/registration.html', context=context)


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def get_success_url(self):
        return reverse_lazy('users:profile')


def profile(request):
    return render(request, template_name='users/profile.html')


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('products:shop'))


class Logout(View):
    def get(self, request, *args, **kwargs):
        return render(request, template_name='users/logout.html')


class UserProfileView(UpdateView):
    model = User
    # form_class = UserProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:login')

    def get_succsess_url(self):
        return reverse_lazy('users:profile', args=self.object.id)

ecommerce/users/templates/users/login.html
{% extends 'base.html' %} {% block content %}


<div>
        {% if messages or form.non_field_errors %}
            <div class="alert
            {% if messages %} alert-success {% else %} alert-warning {% endif %}
                alert-dismissible fade show" role="alert"
                    style="margin-top: 50px;">
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% else %}
                    {{ form.non_field_errors }}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}

    <form
    method="post"
    class="registration__form registration__form--login"
    action="{% url 'users:login' %}"
    >
    {% csrf_token %}
    
    <div class="registration__group registration__group--login">
        <label for="registration__email" class="registration__label"
        >Username</label
        >
        {{ form.username }}
    </div>
    <div class="registration__group registration__group--login">
        <label for="registration__password1" class="registration__label"
        >Password</label
        >
        {{ form.password }}
    </div>
    <div class="registration__options">
        <div><span>Remember me?</span></div>
        <a href="{% url 'users:registration' %}" class="u-accent"
        >Don't registred?</a
        >
    </div>
    <div class="registration__buttons">
        <button type="reset" class="button--secondary">Reset</button>
        <button type="submit" class="button--primary">Submit</button>
    </div>
</form>
</div>
{% endblock %}

ecommerce/users/templates/users/profile.html
{% extends 'base.html' %} {% block content %}
<h2 class="u-accent">Profile</h2>
<form action="{% url 'users:logout' %}">
    <button type="submit" class="button--thridth">Logout</button>
</form>
{% endblock %}

ecommerce/users/templates/users/registration.html
{% extends 'base.html' %} 
{% block content %}

<div class="content registration">
    <div class="registration__description">
        <p>
            This is an <strong>academic</strong> project,
            <br />so you<strong> don't need to use real </strong> credentials.
            <hr />
            However, <strong>  email verification works correctly</strong>, so you can test this
            feature.
        </p>
    </div>
    <form
        method="post"
        class="registration__form"
        action="{% url 'users:registration' %}"
    >
        {% csrf_token %}

        {% if form.non_field_errors %}
            <div class="form-errors">
                {% for error in form.non_field_errors %}
                    <p class="error">{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <div class="registration__group">
            <label for="registration__first_name" class="registration__label"
                >First Name</label
            >
            {{ form.first_name }}
        </div>

        <div class="registration__group">
            <label
                for="{{ form.last_name.id_for_label }}"
                class="registration__label"
                >Last Name</label
            >
            {{ form.last_name }}
        </div>

        <div class="registration__group">
            <label for="registration__username" class="registration__label"
                >Username</label
            >
            {{ form.username }}
        </div>

        <div class="registration__group">
            <label for="registration__email" class="registration__label"
                >Email</label
            >
            {{ form.email }}
        </div>

        <div class="registration__group">
            <label for="registration__password1" class="registration__label">Password</label>
            {{ form.password1 }}
            {% for error in form.password1.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="registration__group">
            <label for="registration__password2" class="registration__label">Confirm Password</label>
            {{ form.password2 }}
            {% for error in form.password2.errors %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </div>

        <div class="registration__group registration__buttons">
            <button type="reset" class="button--secondary">Reset</button>
        </div>
        <div class="registration__group registration__buttons">
            <button type="submit" class="button--primary">Submit</button>
        </div>
        <div class="registration__group">
            <a href="{% url 'users:login' %}" class="u-accent">Back to login</a>
        </div>
    </form>
</div>
{% endblock %}