ecommerce/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name="cart"),
    path('add_cartitem/<int:product_id>',
         views.add_cartitem, name="add_cartitem"),
    path('remove_cartitem/<int:cartitem_id>',
         views.remove_cartitem, name="remove_cartitem"),

]

ecommerce/ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

from ecommerce import settings
from orders.views import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', 'products')),
    path('orders/', include('orders.urls', 'orders')),
    path('cart/', include('cart.urls', 'cart')),
    path('account/', include('users.urls', 'users')),
]


handler404 = page_not_found

ecommerce/products/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductsListView.as_view(), name='shop'),
    path('about', views.about, name='about'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product_page'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce/products/models.py
from django.db import models
from django.urls import reverse


class Brand(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    brand_logo = models.FileField(upload_to='brands/')
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    name = models.CharField(max_length=255, db_index=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True)
    release_year = models.PositiveIntegerField(blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, blank=True, related_name='products')
    tags = models.ManyToManyField('Tag', blank=True, related_name='products')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


def get_brand_image_path(instance, filename):
    return f'products/{instance.product.brand.name}/{filename}'


class PhoneSpecs(models.Model):
    product = models.OneToOneField(
        Product, on_delete=models.CASCADE, related_name='specs')
    network_type = models.CharField(max_length=50)
    battery = models.PositiveIntegerField(help_text="mAh")
    screen_size = models.DecimalField(
        max_digits=4, decimal_places=2, help_text="inches")
    screen_type = models.CharField(max_length=50, blank=True, null=True)
    resolution = models.CharField(max_length=20, blank=True, null=True)
    colors = models.PositiveIntegerField(blank=True, null=True)
    weight = models.PositiveIntegerField(
        blank=True, null=True, help_text="grams")
    dimensions = models.CharField(max_length=50, blank=True, null=True)
    sim_type = models.CharField(max_length=20, blank=True, null=True)
    sim_slots = models.PositiveIntegerField(default=1)

    memory_internal = models.CharField(max_length=50, blank=True, null=True)
    memory_card_support = models.BooleanField(default=False)

    has_sms = models.BooleanField(default=True)
    has_mms = models.BooleanField(default=False)
    has_infrared = models.BooleanField(default=False)
    has_bluetooth = models.BooleanField(default=False)
    has_wap = models.BooleanField(default=False)
    has_gprs = models.BooleanField(default=False)
    has_camera = models.BooleanField(default=False)
    has_radio = models.BooleanField(default=False)
    has_mp3 = models.BooleanField(default=False)
    has_games = models.BooleanField(default=False)
    java_support = models.BooleanField(default=False)

    form_factor = models.CharField(max_length=20, blank=True, null=True)
    ringtones = models.CharField(max_length=50, blank=True, null=True)


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='images')
    alt_text = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to=get_brand_image_path)
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return self.product.name


class Tag(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.title


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    description = models.TextField(blank=True, null=True)
    parent_category = models.ForeignKey(
        'self', on_delete=models.SET_NULL, null=True, blank=True, related_name='subcategories'
    )
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

ecommerce/products/forms.py
from .models import Product, Brand
from django import forms


class SearchForm(forms.Form):

    brand = forms.ModelMultipleChoiceField(queryset=Brand.objects.all(
    ), widget=forms.CheckboxSelectMultiple(attrs={'class': 'content__brand-checkbox'}), required=False,)
    release_year = forms.IntegerField(
        widget=forms.NumberInput(attrs={
            'type': 'range',  
            'min': '1995',
            'max': '2010',
            'step': '1',
            'class': 'content__year-slider'
        }),
        required=False,
        min_value=1995,
        max_value=2010
    )

    # price_min = forms.DecimalField(required=False)
    # price_max = forms.DecimalField(required=False)

    # def clen_relise_year():
    #     year = self.cleaned data

    #     if 2000 > relise_year > 2010:
    #         raise ValueError

ecommerce/products/views.py
from django.db.models import Prefetch
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, FileResponse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.safestring import mark_safe
from .models import Product, Category, Tag, ProductImage, PhoneSpecs
from .forms import SearchForm


class ProductsListView(ListView):
    model = Product
    template_name = 'products/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        queryset = super().get_queryset().prefetch_related(
            Prefetch('images', queryset=ProductImage.objects.order_by(
                '-is_main', 'id'))
        )
        release_year = self.request.GET.getlist('release_year')
        release_year = [int(year) for year in release_year if year.isdigit()]

        for i in release_year:
            print(type(i))

        filters = {
            'brand__id__in': self.request.GET.getlist('brand'),
            'release_year__in': release_year,
        }

        for key, value in filters.items():
            if value:
                queryset = queryset.filter(**{key: value})

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = self.request.GET.copy()
        if 'release_year' in data:
            data.setlist('release_year', [int(x) for x in data.getlist(
                'release_year') if x.isdigit()])
        context['form'] = SearchForm(data)
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        slug = self.kwargs.get('slug')
        product = get_object_or_404(
            Product.objects.prefetch_related('images'),
            slug=slug
        )
        context['products'] = product
        return context


def about(request):
    return HttpResponse("about")

ecommerce/products/templates/products/brand_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ecommerce/products/templates/products/index.html
{% extends 'base.html' %} 
{% load static %} 
{% load product_card %} 

{% block content %}
<div class="content__shop-page">
    <div class="content__form-filter">
        <div class="content__filter-resize button--secondary"><span>Filter</span></div>

        <form class="content__filter-fields">
            <div class="content__field-wrapper">
                <div class="content__field-name"><span>{{ form.brand.label }}</span></div> 
                <div class="content__brand-wrapper">
                    {% for checkbox in form.brand %}
                        <label class="content__brand-label">
                            {{ checkbox.tag }}
                            {{ checkbox.choice_label }}
                        </label>
                    {% endfor %}
                </div>  
            </div>  
            <div class="content__field-wrapper">
                <label class="content__field-name">Release year:
                </label>
                <span id="year-value">----</span>
                {{ form.release_year }}
            </div>
            
            <div class="content__buttons-container ">
                <button type="reset" class="button--secondary">Reset</button>
                <button type="submit" class="button--primary">Submit</button>
            </div>
        </form>  
        

    </div>  
    <div class="content__catalog">
        {% if products %} 
            {% for prod in products %} 
                {% get_product_card prod %}
            {% endfor %}
        {% else %}
            <p>Nothing founded</p>
        {% endif %}
    </div>
    <script>
        const slider = document.getElementById('id_release_year');
        const output = document.getElementById('year-value');
        output.textContent = slider.value;
        slider.oninput = function() {
            output.textContent = this.value;
        };
</script>
</div>
It is {% now "jS F Y H:i:s" %} 
{% endblock %}

ecommerce/products/templates/products/product_card.html
<article class="article">
    <a
        class="article__product-card"
        href="{% url 'products:product_page' product.slug %}"
    >
        <img
            class="article__brand-logo"
            src="{{product.brand.brand_logo.url }}"
        />

        <h3 class="article__product-name"><i>{{ product.name }}</i></h3>

        <div class="article__carousel">
            {% for img in product.images.all %}
            <div
                class="article__carousel-item {% if img.is_main %}article__carousel-item--active{% endif %}"
            >
                <img src="{{ img.image.url }}" alt="{{ img.alt_text }}" />
            </div>
            {% endfor %}
        </div>

        <div class="article__product-info product-info">
            <p class="article__release-year">
                <span>{{ product.release_year }}</span>
            </p>
            <p class="article__price">
                <span>{{ product.price }} $</span>
            </p>
        </div>
    </a>
    <a class="article__add-button button--primary" href="{% url 'cart:add_cartitem' product.id %}">Add</a>
    <div class="article__buttons-container">
        <button class="article__prev">&#10094;</button>
        <button class="article__next">&#10095;</button>
    </div>
</article>

ecommerce/products/templates/products/product_page.html
{% extends 'base.html' %} {% load static %}
{% block content%}
    <h1>{{ product.name }}</h1>
    <a>{{ product.brand.name }}</a>
    <div class="carousel"> 
    {% for img in product.images.all  %}
        <div class="carousel-item {% if img.is_main %}active{% endif %}">
            <img src="{{ img.image.url }}"alt="{{ img.alt_text }}">
        </div>
    {% endfor %}

</div> {% endblock %}