ecommerce/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name="cart"),
    path('add_cartitem/<int:product_id>',
         views.add_cartitem, name="add_cartitem"),
    path('remove_cartitem/<int:cartitem_id>',
         views.remove_cartitem, name="remove_cartitem"),

]

ecommerce/ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

from ecommerce import settings
from orders.views import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', 'products')),
    path('orders/', include('orders.urls', 'orders')),
    path('cart/', include('cart.urls', 'cart')),
    path('account/', include('users.urls', 'users')),
]


handler404 = page_not_found

ecommerce/products/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductsListView.as_view(), name='shop'),
    path('about', views.about, name='about'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product_page'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('registration', views.registration, name='registration'),
    path('login', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    # path('logout', views.Logout.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),

]

ecommerce/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>{{title}}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Project for learn django" />
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
        <!-- {% block stylesheet %} -->
        <!-- {% endblock %} -->
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
    </head>
    <body>
        <header class="header">
            <div class="header__container container">
                <a href="{% url 'products:shop' %}">
                    <h1 class="header__title">Old Phones shop</h1>
                </a>
                <nav class="header__nav-menu">
                    <div class="header__hamburger" id="hamburger">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>

                    <div class="header__links-container">
                        {% for m in get_nav_menu %}
                            {% if m.title == "Account" and user.is_authenticated %}
                            <div class="header__profile" >
                                <a href="{% url 'users:profile' %}" class="header__nav-link">{{ user.username|default:"Account"|capfirst }}</a>
                                <div class="header__profile-options">
                                    <a href="{% url 'users:profile' %}" class="header__nav-link">Profile</a>
                                    <a href="{% url 'cart:cart' %}" class="header__nav-link">Cart</a>
                                    <a href="{% url 'users:logout' %}" class="header__nav-link">Logout</a>
                                </div>
                            </div>
                            {% elif m.title == "Cart" and user.is_authenticated %}
                            {% else %}
                                <a href="{% url m.url_name %}" class="header__nav-link">{{ m.title }}</a>
                            {% endif %}
                        {% endfor %}    
                    </div>
                </nav>
            </div>
        </header>
        <main class="content container">{% block content%} {% endblock %}</main>
        <!-- <footer class="footer">{% include './footer.html' %}</footer> -->
        <div class="overlay"></div>
    </body>
    <script src="{% static 'products/js/script.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</html>

ecommerce/templates/footer.html
{% load static %}

<footer class="footer">
    <p>&copy; 2025 Мой сайт </p>
</footer>